### ISSUE TITLE
Contribution stats from Gitlab

### ISSUE THREAD

**Issue by DieterHolvoet** [LordDashMe/github-contribution-stats#10]
Congrats on this repo, I like the idea and the widget looks nice! I was wondering if you would consider adding the possibility to generate widgets for contribution sources other than Github, such as Gitlab. It would be cool to have widgets per Gitlab instance, e.g. `gitlab.com` and `git.drupalcode.org` (for Drupal contributions).

**Comment by LordDashMe** [comment]
Hello! @DieterHolvoet. Actually this is a great idea, yes right now we only support source data that came from Github. I will check other sources (ex. gitlab.com) if they have an open API to use :-). Thank you!

**Comment by DieterHolvoet** [comment]
Sure, Gitlab has an API: https://docs.gitlab.com/ee/api/

**Comment by LordDashMe** [comment]
> Sure, Gitlab has an API: https://docs.gitlab.com/ee/api/

I see! that's great and they also supports GraphQL. Actually if you are free you can also contribute this feature :-), the project is open for any code changes :-)

**Comment by akashshyamdev** [comment]
Hey there! I'd like to take this up, but I'm not really aware of how this is done. I know Javascript, HTML, CSS and NodeJS. Could you point me out to some docs?
