### ISSUE TITLE
[ Feature Request ] : Different Themes

### ISSUE THREAD

**Issue by Siddhant-K-code** [LordDashMe/github-contribution-stats#12]
This feature request is for the customization of cards with different themes.

**Comment by LordDashMe** [comment]
Hello, @Siddhant-K-code. 

Thanks for opening this issue, yes we are glad if this feature is existing in the project.
There are some plan to add this feature, but if you have any idea or suggestion feel free to share it! :+1:

**Comment by LordDashMe** [comment]
https://github.com/LordDashMe/github-contribution-stats/issues/7
