### ISSUE TITLE
Displays 0 for code reviews

### ISSUE THREAD

**Issue by bolinocroustibat** [LordDashMe/github-contribution-stats#19]
I'm reviewing around 5/10 PRs per month, but the widget displays 0 code reviews. Is this because it's on private repos?

Thanks!

(PS: I'm happy to be added in the users lists)

**Comment by LordDashMe** [comment]
Hi, @bolinocroustibat. Thank you for reporting this possible issue, we will check if the code reviews and other metrics counts are only available for public repos.

Also, we added you in the list of users of this project. Thank you for using it! <3
