### ISSUE TITLE
Cool stats

### ISSUE THREAD

**Issue by oskar-gmerek** [LordDashMe/github-contribution-stats#48]
Hi there,

I migrate from other contributtion stats, I found out that `github-contribution-stats` are looks better.
I will be happy to be mentioned as a user of `github-contribution-stats`.

<img width="929" alt="Zrzut ekranu 2023-08-19 o 16 15 12" src="https://github.com/LordDashMe/github-contribution-stats/assets/53402105/ee8b4fdf-01b6-4485-85f7-58f8c05de29b">

**Comment by LordDashMe** [comment]
We thank you for using this project @oskar-gmerek 🎉
