### ISSUE TITLE
Just started using contribution stats

### ISSUE THREAD

**Issue by Web-learning** [LordDashMe/github-contribution-stats#52]
Hello. Thanks for contribution stats. Still new here. And I have never submitted an issue either. Thought I'd ask to have my name added to the list. Much appreciated

**Comment by Goldmaa** [comment]
@LordDashMe Would be useful

**Comment by LordDashMe** [comment]
Hey @Web-learning, we thank you for using this contribution stats! 🎉  your name is now added to the list 👍
