### ISSUE TITLE
Currently Using github contribution stats!

### ISSUE THREAD

**Issue by MalekMansour** [LordDashMe/github-contribution-stats#60]
I am currently using the github contribution stats at https://github.com/MalekMansour and would like to be added to the list, thank you!

**Comment by LordDashMe** [comment]
Thanks for using the project @MalekMansour and feel free to contribute if you have some cool ideas to improve it 👍

**Comment by suhaanigurjar** [comment]
Hi! I've been using this stats card too for a while now. 
What list are we talking about here?

**Comment by MalekMansour** [comment]
There is a list of names of the people who use this stats card on the README file of this repo. You can ask for your name to be added!

**Comment by suhaanigurjar** [comment]
Oh okay, thank you!
