### ISSUE TITLE
New User!

### ISSUE THREAD

**Issue by suhaanigurjar** [LordDashMe/github-contribution-stats#64]
Hi! Congrats on this repo, I love the idea and the widget looks great!
I am currently using the github contribution stats at https://github.com/suhaanigurjar and would like to be added to the list, thank you!

**Comment by LordDashMe** [comment]
Hello @suhaanigurjar! thanks for using this project and we appreciate your feedback. Feel free to contribute to this project if you have something in mind!  🙌  👍

**Comment by LordDashMe** [comment]
Added you in the list, cheers! 🍻

**Comment by suhaanigurjar** [comment]
> Hello @suhaanigurjar! thanks for using this project and we appreciate your feedback. Feel free to contribute to this project if you have something in mind! 🙌 👍

will try to for sure! 🙌
